# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 612bf88c373f784a837e32a128494c59b2a011766698c6268222da6e6e01f8bac1c2f744ab6a82e120f539415437f67c6d6305b82e606651ea3fe39aefadf66f

test:
  secret_key_base: 90614d911fd56418c58467941dc2ff83a1fe05cec410ad204ec093d6262a1e2dc28521a993b8b7c2764173e5437e764f3491454f9cf531e13ba7a7349972d5c3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
